### ISSUE TITLE
How to import css style beside component?

### ISSUE THREAD

**Issue by gleissonneves** [IsraelDCastro/my-library-vue-ts#2]
Case: I am using a component exported from my library, but when using it, the style is not persisted

Example: 
it turns out that it shows the unstyled component;
![Captura de tela de 2023-01-19 02-16-58](https://user-images.githubusercontent.com/53718407/213361240-b24c9465-b27e-432c-ad1d-98018f7f56cb.png)

When to show style
![Captura de tela de 2023-01-19 02-20-05](https://user-images.githubusercontent.com/53718407/213361682-78007aa4-b643-46ae-945a-f42c527e4a94.png)

**Comment by gleissonneves** [comment]
Use vite-plugin-css-injected-by-js inject CSS in component

Correction step by step

Install vite-plugin-css-injected-by-js;
In file ```vite.config.ts``` adding:
`plugins: [
   ...
   cssInjectedByJsPlugin()
   ...
]`

**Comment by IsraelDCastro** [comment]
Thank you for the suggestions, I'll check the PR and try it on.
